name: reamp
description: VR therapy to beat MRT anxiety

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.3.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  vr_video:
    path: ../vr_video
  
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.5
  package_info_plus: ^3.0.2
  flutter_markdown: ^0.6.7
  firebase_storage: ^11.0.10
  uuid: ^3.0.5
  encrypt: ^5.0.1
  confetti: ^0.7.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.4.0
  video_player: ^2.3.0
  flutter_local_notifications: ^12.0.4
  timezone: ^0.9.1
  rxdart: ^0.27.1
  firebase_core: ^2.3.0
  firebase_database: ^10.0.14


 

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - videos/
    - crypt/
